// Code generated by go-swagger; DO NOT EDIT.

// Package restapi E-Commerce Stocks Tracker
//
//  A service for keeping an accurate list of products and their stocks up to date
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 0.1.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//    - text/plain
//
// swagger:meta
package restapi
