// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: product.sql

package db

import (
	"context"
)

const getProductBySKU = `-- name: GetProductBySKU :one
SELECT id, sku, name, created_at, updated_at FROM products WHERE sku = $1 LIMIT 1
`

func (q *Queries) GetProductBySKU(ctx context.Context, sku string) (Product, error) {
	row := q.queryRow(ctx, q.getProductBySKUStmt, getProductBySKU, sku)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
