// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	ConsumeStock(ctx context.Context, arg ConsumeStockParams) error
	GetProductBySKU(ctx context.Context, sku string) (Product, error)
	GetProductStockCountBySKU(ctx context.Context, sku string) (int64, error)
	GetStockByProductSKUAndCountryCodeForUpdate(ctx context.Context, arg GetStockByProductSKUAndCountryCodeForUpdateParams) (GetStockByProductSKUAndCountryCodeForUpdateRow, error)
	ListProductStocksBySKU(ctx context.Context, sku string) ([]ListProductStocksBySKURow, error)
}

var _ Querier = (*Queries)(nil)
