// Code generated by go-swagger; DO NOT EDIT.

package product

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetProductBySkuHandlerFunc turns a function with the right signature into a get product by sku handler
type GetProductBySkuHandlerFunc func(GetProductBySkuParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetProductBySkuHandlerFunc) Handle(params GetProductBySkuParams) middleware.Responder {
	return fn(params)
}

// GetProductBySkuHandler interface for that can handle valid get product by sku params
type GetProductBySkuHandler interface {
	Handle(GetProductBySkuParams) middleware.Responder
}

// NewGetProductBySku creates a new http.Handler for the get product by sku operation
func NewGetProductBySku(ctx *middleware.Context, handler GetProductBySkuHandler) *GetProductBySku {
	return &GetProductBySku{Context: ctx, Handler: handler}
}

/* GetProductBySku swagger:route GET /products/{sku} Product getProductBySku

Get a product by SKU

Get product entry by SKU

*/
type GetProductBySku struct {
	Context *middleware.Context
	Handler GetProductBySkuHandler
}

func (o *GetProductBySku) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetProductBySkuParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
