// Code generated by go-swagger; DO NOT EDIT.

package product

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetProductStocksBySkuHandlerFunc turns a function with the right signature into a get product stocks by sku handler
type GetProductStocksBySkuHandlerFunc func(GetProductStocksBySkuParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetProductStocksBySkuHandlerFunc) Handle(params GetProductStocksBySkuParams) middleware.Responder {
	return fn(params)
}

// GetProductStocksBySkuHandler interface for that can handle valid get product stocks by sku params
type GetProductStocksBySkuHandler interface {
	Handle(GetProductStocksBySkuParams) middleware.Responder
}

// NewGetProductStocksBySku creates a new http.Handler for the get product stocks by sku operation
func NewGetProductStocksBySku(ctx *middleware.Context, handler GetProductStocksBySkuHandler) *GetProductStocksBySku {
	return &GetProductStocksBySku{Context: ctx, Handler: handler}
}

/* GetProductStocksBySku swagger:route GET /products/{sku}/stocks Product getProductStocksBySku

Get a product's stocks by SKU

Get product's stocks entries by SKU

*/
type GetProductStocksBySku struct {
	Context *middleware.Context
	Handler GetProductStocksBySkuHandler
}

func (o *GetProductStocksBySku) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetProductStocksBySkuParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
